[tool.poetry]
name = "crew-pools"
version = "0.1.0"
description = ""
authors = ["Pedro Lucas Lima <lclpedro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
streamlit = "^1.42.1"
requests = "^2.32.3"
lru-cache = "^0.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
